// Every phrase that can be spoken in Australia. `node scripts/world-voice-lines.mjs` turns this into voice-lines.json.
// (Plain strings only: this file is also read by Node, so it imports nothing. NAME matches KID_NAME.)
const NAME = 'Kaylee'

export const L = {
  name: 'Australia',
  intro: [`G'day, ${NAME}! I'm Pip, a baby kangaroo!`, "G'day means hello! Will you help me get ready for my party?"],
  hubFirst: 'Tap a spot on the map!',
  hubNext: `Where should we go next, ${NAME}?`,
  hubParty: 'Everyone is here! Tap the party!',
  partyLocked: 'Get all five stamps to start the party!',
  trophyWin: `${NAME}, you did it! You won the Australia Explorer trophy!`,
  trophyRoom: `${NAME}, Australia Explorer! From Australia.`,

  outback: {
    story: "Welcome to the outback! It's hot and dry here.",
    pack: 'Give Pip the things she needs for the hot sun!',
    hat: 'A sun hat for shade!',
    glasses: 'Sunglasses for the bright sun!',
    water: 'Water to drink in the heat!',
    brrr: "Brrr? No way! It's hot in the outback!",
    ready: "Pip is ready! Let's hop!",
    hop3: 'Tap to hop! Hop three times to the water hole.',
    splash: 'Splash! A water hole!',
    hop5: 'Now hop five times to Uluru, the big red rock!',
    pouch: "Pip's mama! Pip jumps into her pouch!",
  },
  forest: {
    story: "This is Koko the koala. She's so hungry!",
    feed2: 'Feed Koko two gum leaves!',
    feed4: 'Now feed her four leaves!',
    only: 'Koalas only eat gum leaves!',
    yawn: 'Yawn! Koalas sleep almost all day.',
    lullaby: 'Tap the notes to sing Koko a lullaby!',
  },
  reef: {
    story: ["Sparkle put on her snorkel! Let's dive into the Great Barrier Reef!", "It's so big, you can see it from space!"],
    find: {
      turtle: 'Find the sea turtle!',
      clownfish: 'Find the clownfish!',
      starfish: 'Find the starfish!',
      octopus: 'Find the octopus! It likes to hide.',
    },
    found: {
      turtle: 'You found Shelly the sea turtle!',
      clownfish: 'You found the clownfish!',
      starfish: 'You found the starfish!',
      octopus: 'You found the octopus! It has eight arms!',
    },
    thats: {
      turtle: "That's the sea turtle!",
      clownfish: "That's a clownfish!",
      starfish: "That's a starfish!",
      octopus: "That's the octopus!",
      crab: "That's a crab!",
      puffer: "That's a puffer fish!",
      shell: "That's a seashell!",
    },
  },
  stars: {
    story: 'At night in Australia, you can see the Southern Cross stars!',
    tap: 'Tap the five twinkly stars!',
    found: 'You found the Southern Cross!',
    onFlag: "The stars are on Australia's flag!",
    drag: 'Drag the big star onto the flag!',
    seven: 'The big star has seven points!',
    which: "Which one is Australia's flag?",
    hint: 'Look for the stars you found!',
  },
  postcard: {
    story: "Let's color a postcard from the beach to send home!",
    how: 'Pick a color, then tap to paint!',
    send: 'Tap send when you are done!',
    gday: "G'day, mate! In Australia, mate means friend.",
  },
  party: {
    story: 'Party time at the Sydney Opera House!',
    tap: 'Tap each friend to make them dance!',
    mama: `G'day, ${NAME}! Thanks for helping Pip!`,
    koko: 'Yum! Thanks for the gum leaves!',
    shelly: 'Hello from the reef!',
    kooky: 'Ha ha ha! Kookaburras love to laugh!',
    pat: "I'm Pat the platypus! Hooray!",
    fireworks: 'Sydney has some of the biggest fireworks in the world!',
    thanks: `Thank you, ${NAME}! You're a true Aussie mate!`,
  },
  stickers: {
    kangaroo: 'Kangaroo sticker! Kangaroos can only hop forward, never backward!',
    koala: 'Koala sticker! A baby koala is called a joey, just like a kangaroo!',
    turtle: 'Sea turtle sticker! Sea turtles lived when the dinosaurs did!',
    kookaburra: 'Kookaburra sticker! Kookaburras sound like they are laughing!',
    platypus: 'Platypus sticker! A platypus has a bill like a duck!',
  },
  facts: {
    weather: 'Much of Australia is hot and sunny, with big dry deserts.',
    hello: "In Australia, people say G'day! It means hello!",
    christmas: 'In Australia, Christmas comes in summer! Beach day!',
    animals: 'Kangaroos, koalas and platypuses all live in Australia!',
    opera: 'The Sydney Opera House looks like big white sails!',
    continent: 'Australia is a country and a whole continent!',
  },
  passport: 'This is Australia! Tap a picture to learn more.',
}
