import { test, expect } from '@playwright/test'

const names = ['Campground Adventure', 'Busy Beach Day', 'Woodland Fun Fair', 'Snowy Village', 'Flower Market']
for (const viewport of [{ width: 820, height: 1180 }, { width: 1180, height: 820 }, { width: 1024, height: 1366 }, { width: 667, height: 375 }, { width: 844, height: 390 }]) {
  test(`unicorn hunts at ${viewport.width}x${viewport.height}`, async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', e => errors.push(e.message))
    page.on('console', m => { if (m.type() === 'error') errors.push(m.text()) })
    await page.setViewportSize(viewport)
    await page.goto('/')
    await page.getByRole('button', { name: /let's play/i }).click()
    await page.getByRole('button', { name: 'Unicorn Hide & Seek', exact: true }).click()
    for (const name of names) {
      await page.getByRole('button', { name, exact: true }).click()
      await expect(page.getByLabel('0 of 5 unicorns found')).toBeVisible()
      const first = page.getByRole('button', { name: 'Unicorn 1', exact: true })
      const bounds = await first.boundingBox()
      expect(bounds!.width).toBeGreaterThanOrEqual(44)
      expect(bounds!.height).toBeGreaterThanOrEqual(44)
      await page.getByRole('button', { name: 'Zoom in', exact: true }).click()
      await page.getByRole('button', { name: 'Hint', exact: true }).click()
      await expect(first).toHaveClass(/is-hint/)
      await first.click()
      await expect(page.getByLabel('1 of 5 unicorns found')).toBeVisible()
      await page.getByRole('button', { name: 'Zoom out', exact: true }).click()
      for (let n = 2; n <= 5; n++) await page.getByRole('button', { name: `Unicorn ${n}`, exact: true }).click()
      await expect(page.getByRole('button', { name: 'Next scene' })).toBeVisible()
      await expect(page.getByLabel('5 of 5 unicorns found')).toBeVisible()
      if (name === names[0]) await page.screenshot({ path: `/tmp/seek-complete-${viewport.width}.png` })
      await page.getByRole('button', { name: 'Back to scenes' }).click()
    }
    await expect(page.getByLabel('Completed')).toHaveCount(5)
    await page.reload()
    await page.getByRole('button', { name: /let's play/i }).click()
    await expect(page.getByLabel('Completed')).toHaveCount(5)
    await page.getByRole('button', { name: names[0], exact: true }).click()
    await page.getByRole('button', { name: 'Play again', exact: true }).click()
    await expect(page.getByLabel('0 of 5 unicorns found')).toBeVisible()
    await page.screenshot({ path: `/tmp/seek-play-${viewport.width}.png` })
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)
    expect(overflow).toBe(false)
    expect(errors).toEqual([])
  })
}
test('phone rotate prompt preserves the hunt and allows returning to the shelf', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/seek/camp')
  await page.getByRole('button', { name: /let's play/i }).click()
  await expect(page.getByRole('heading', { name: 'Turn your phone sideways' })).toBeVisible()
  await page.getByRole('button', { name: '‹ Back to scenes', exact: true }).click()
  await page.getByRole('button', { name: names[0], exact: true }).click()
  await page.setViewportSize({ width: 844, height: 390 })
  await expect(page.getByRole('heading', { name: 'Turn your phone sideways' })).toBeHidden()
  await page.getByRole('button', { name: 'Unicorn 1', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: '/tmp/seek-rotate.png' })
  await page.setViewportSize({ width: 844, height: 390 })
  await expect(page.getByLabel('1 of 5 unicorns found')).toBeVisible()
})
