// Every phrase that can be spoken in Egypt. `node scripts/world-voice-lines.mjs` turns this into voice-lines.json.
// (This file is also read by Node, so it imports nothing. NAME matches KID_NAME.)
// Plain strings are Sparkle, the guide: she gives the instructions. Friends say their own story and reaction lines in
// their own voices (see cast.json), and their puppets move their mouths while they talk.
const NAME = 'Kaylee'
const as = (voice: string) => (text: string) => ({ text, voice })
const miu = as('miu')
const jamal = as('jamal')
const sphinx = as('sphinx')
const tutu = as('tutu')
const hippo = as('hippo')
const fennec = as('fennec')
const ibis = as('ibis')
const COUNT = ['One!', 'Two!', 'Three!', 'Four!', 'Five!']

export const L = {
  name: 'Egypt',
  intro: [miu(`Ahlan, ${NAME}! I'm Miu the kitten!`), miu('Ahlan means hello! Come explore Egypt with me!')],
  hubFirst: miu('Tap a spot on the map!'),
  hubNext: miu(`Where to next, ${NAME}?`),
  hubParty: miu('Everyone is here! Tap the light show!'),
  partyLocked: miu('Get all the stamps to start the light show!'),
  trophyWin: `${NAME}, you did it! You won the Egypt Explorer trophy!`,
  trophyRoom: `${NAME}, Egypt Explorer! From Egypt.`,
  tickle: {
    miu: [miu('Purr! That tickles!'), miu('Meow! Hee hee!')],
    jamal: [jamal('Harrumph! Hello, little one.'), jamal('Mmm, I love sweet dates!')],
    sphinx: [sphinx('Ho ho! That tickles!')],
    tutu: [tutu('Hee hee! My bandages are ticklish!')],
  },

  pyramid: {
    story: jamal("I'm Jamal the camel. Let's build a pyramid!"),
    drag: 'Drag the stone onto the glowing spot!',
    count: COUNT.slice(0, 3).map(miu),
    bottom: 'Three big stones on the bottom!',
    small: 'Now pick the smaller stone. Small stones go on top!',
    tooBig: jamal('Oof! Too big for up there!'),
    middle: 'Two stones in the middle!',
    top: 'Now one little stone on the very top!',
    cap: 'Last, the golden cap! It is a triangle!',
    done: miu('Wow! Our pyramid is shining!'),
    fact: "Long ago, Egyptians built pyramids for their kings, the pharaohs!",
  },
  passage: {
    story: miu("Let's sneak inside the pyramid! It's dark in here!"),
    drag: 'Drag Miu through the tunnel to the scarab!',
    two: 'Now find two scarabs!',
    deeper: 'Find the way to the treasure room!',
    scarab: miu('A scarab! Egyptians loved these beetles.'),
    count: COUNT.slice(0, 2).map(miu),
    bat: miu('Shh! A sleepy bat! Not this way.'),
    wall: miu('Not this way! Hee hee.'),
    treasure: 'The treasure room! Tap the golden box!',
    mask: 'This gold mask was made for a boy king called Tut!',
    tutu: tutu(`Yawn! Ahlan, ${NAME}! I'm Tutu!`),
    nap: tutu('I napped for thousands of years! Hee hee!'),
  },
  nile: {
    story: miu("All aboard! Let's sail down the Nile River!"),
    steer: 'Drag the boat up and down to catch the lotus flowers!',
    hippo: hippo('Bump! Hee hee, hello!'),
    farm: 'The farm is thirsty! Pull the bucket down three times!',
    farm5: 'This farm is thirsty too! Pull the bucket five times!',
    count: COUNT.map(miu),
    green: miu('Look! The water makes the plants grow!'),
    desert: 'Egypt is mostly sandy desert. The Nile makes it green!',
    longest: 'The Nile is one of the longest rivers in the world!',
  },
  sphinx: {
    story: miu('Oh no! Someone is buried in the sand!'),
    rub: 'Rub the sand away!',
    sneeze: sphinx('Ah... ah... achoo!'),
    hello: sphinx("Thank you! I'm the Sphinx!"),
    paws: 'Now brush the sand off his paws!',
    twoPaws: 'Two big lion paws!',
    back: 'Now brush off his back!',
    lion: "The Sphinx has a lion's body and a person's head!",
    pieces: 'You found pieces of an old pot! Put it back together!',
    potDone: miu('Good as new!'),
    nose: sphinx(`Thank you, ${NAME}! Hmm, have you seen my nose?`),
    noseAns: miu('Hee hee! His nose fell off a long, long time ago!'),
  },
  scribe: {
    story: miu('Long ago, Egyptians wrote with little pictures called hieroglyphs!'),
    name: `Let's write your name, ${NAME}, like a pharaoh!`,
    hold: 'Press and hold the stamp that matches!',
    k: 'K says kuh! Find the basket!',
    a: 'A says ay! Find the bird!',
    y: 'Y says yuh! Find the two reeds!',
    l: 'L says lll! Find the lion!',
    e: 'E says ee! Find the reed!',
    e2: 'E again! One more reed!',
    hint: 'Look for the same picture!',
    done: miu(`${NAME}! That says ${NAME}!`),
    cartouche: 'Kings and queens wrote their names in an oval like this!',
  },
  market: {
    story: miu("Welcome to my market stall! Let's make koshari!"),
    order: jamal('Ahlan! One koshari, please!'),
    recipe: 'Follow the recipe! First, the rice!',
    lentils: 'Next, the lentils!',
    pasta: 'Now the pasta!',
    sauce: 'Now the tomato sauce!',
    onions: 'Crispy onions on top!',
    wrong: 'Look at the recipe! What comes next?',
    yum: 'Koshari is a yummy Egyptian food!',
    shukranJamal: jamal('Shukran!'),
    shukran: miu('Shukran means thank you!'),
    extra: fennec('Ahlan! Extra crispy onions, please!'),
    pinch: 'Add three pinches of onions!',
    count: COUNT.slice(0, 3).map(miu),
    shukranFennec: fennec('Shukran!'),
    tea: hippo('Ahlan! Mint tea, please!'),
    pour: 'Press and hold to pour! Let go at the gold line!',
    whoops: miu('Whoops! A little too much! Hee hee.'),
    shukranHippo: hippo('Shukran!'),
  },
  show: {
    story: miu('The light show is starting!'),
    beam: 'Drag a light onto the pyramids!',
    jamal: jamal('Harrumph! What a pretty show!'),
    tutu: tutu('Hee hee! I love the lights!'),
    hippo: hippo('Hello from the Nile!'),
    sphinx: sphinx('Ho ho! I shine at night!'),
    ibis: ibis('Hello! I love writing too!'),
    fennec: fennec('Yum! Thank you for the koshari!'),
    rope: "Pull the rope to raise Egypt's flag!",
    flag: "Egypt's flag is red, white and black, with a golden eagle!",
    thanks: miu(`Shukran, ${NAME}! You're a true Egypt explorer!`),
  },
  stickers: {
    camel: 'Camel sticker! Camels store fat in their humps for long trips!',
    scarab: 'Scarab sticker! Egyptians thought scarabs were lucky!',
    hippo: 'Hippo sticker! Hippos love the cool Nile water!',
    fennec: 'Fennec fox sticker! Big ears help it stay cool in the desert!',
    ibis: 'Ibis sticker! Egyptians drew this bird in their picture writing!',
    cat: 'Kitty sticker! In Egypt, cats were loved like family!',
  },
  facts: {
    weather: 'Egypt is hot and sunny, and it hardly ever rains!',
    hello: 'In Egypt, people say Ahlan! It means hello!',
    thanks: 'Shukran means thank you in Arabic, the language of Egypt!',
    pyramids: 'The pyramids are more than four thousand years old!',
    nile: 'The Nile River gives Egypt water for farms and for drinking.',
    writing: 'Long ago, Egyptians wrote with pictures called hieroglyphs!',
    cats: 'In ancient Egypt, cats were loved like family!',
    food: 'Koshari is rice, lentils and pasta with yummy sauce!',
    flag: "Egypt's flag is red, white and black, with a golden eagle!",
  },
  passport: 'This is Egypt! Tap a picture to learn more.',
  videos: {
    pyramids: "Want to see the real pyramids?",
    nile: "Let's see the real Nile River!",
    sphinx: "Want to see the real Sphinx?",
    camels: "Let's see real camels!",
  },
}
