// Everything a game needs. Games import ONLY from here (and their own folder):
//   import { say, sounds, ChoiceCards, praise, type GameProps } from '../../sdk'

export type { GameMeta, GameProps } from './types'
export { say, stopSpeaking, lineText, lineVoice, speechLevel, speakingVoice, type Line, type SayOptions } from './speech'
export { sounds } from './sounds'
export { burst, bigCelebration } from './confetti'
export { KID_NAME, wait, randomInt, pick, shuffle, sample, praise, numberWord } from './helpers'
export { useAlive, useSayOnMount, useLandscape, useElementSize, useGameLoop, useSaved } from './hooks'
export { usePuppet, spring, setT, setA, show, clamp, lerp, smooth, bell, span, wobble, type PuppetFrame, type PuppetHandle, type PuppetOptions } from './puppet/core'
export { Buddy, type BuddyAction } from './puppet/Buddy'
export { SparklePuppet, SPARKLE_ACTIONS, type SparkleAction, type SparklePuppetProps } from './puppet/Sparkle'

export { BigButton, type BigButtonProps } from './components/BigButton'
export { ChoiceCards, type Choice, type ChoiceCardsProps } from './components/ChoiceCards'
export { DragArea, Draggable, DropZone, type DraggableProps } from './components/Drag'
export { SortIntoBins, type SortItem, type SortBin, type SortIntoBinsProps } from './components/SortIntoBins'
export { MatchPairs, type Pair } from './components/MatchPairs'
export { TapToReveal } from './components/TapToReveal'
export { TapCounter } from './components/TapCounter'
export { Mascot, type MascotPose } from './components/Mascot'
export { StarProgress } from './components/StarProgress'
export { SayButton } from './components/SayButton'
export { Scene } from './components/Scene'
export { Trophy } from './components/Trophy'

// Advanced interactions (see docs/interactions.md): pointer dragging, snapping, place-anywhere, dress-up.
export { usePointerDrag, toLocal, centerOf, distance, type DragInfo, type PointerDragOptions } from './interact/pointer'
export { PlayArea, Piece, Target, type PieceProps, type TargetProps, type Drop, type PlaceResult } from './interact/PlayArea'
export { JigsawPuzzle, type JigsawPuzzleProps } from './interact/JigsawPuzzle'
export { StickerBoard, countByKind, type Sticker, type Placed, type StickerBoardProps } from './interact/StickerBoard'
export { DressUpStudio, OptionPicker, Swatch, type DressSlot, type DressOption, type DressUpStudioProps, type OptionPickerProps } from './interact/DressUp'
